### ISSUE TITLE
About tf tree

### ISSUE THREAD

**Issue by AriYu** [Nishida-Lab/forest_robot_project#17]
I checked tf tree for adding `/odom` frame and found strange transforms like follow image.
![screenshot from 2016-02-08 23 50 13](https://cloud.githubusercontent.com/assets/8924428/12888764/e45f93a4-cebe-11e5-8a50-14eafc48a705.png)
I added `hokuyo3d_link` before checking tf tree.
I think `base_footprint` should be transformed from `base_link` or nearly root of tree.
Please tell me why it is, thank you.

**Comment by RyodoTanaka** [comment]
@AriYu 
Year, I understand your saying. And, I think It is not good (wrong) statement.
But there is a reason why I set such a strange tf tree. I'll tell you the situation.

First, I set the `base_footprint` be transformed from `base_link`.
Then, I simulated with Gazebo. And I found the `base_link` was moving. That means `base_footprint` was moving.
I thought `base_footprint` should be on the ground and not move (to Z axis direction).
So, I set these strange tf trees.

Of course I know it's not good idea, or may be I think, we don't need to do that.
But I have no idea. Please let me know your idea.

**Comment by MoriKen254** [comment]
I'm not familiar with the issue but let me give something here.

have a look at TF tree of p.310 of `Learning ROS for Robotics Programming 2nd Edition`. all related files about the tree are also available on Github including xacro of a very simple wheel robot.

hope u guys will find some hints from that.

**Comment by AriYu** [comment]
@RyodoTanaka 
OK, I understood.
But, why did you try to transform `base_footprint` from `base_link` ?
I read `Learning ROS for Robotics Programming 2nd Edition`, 
the book say
`base_footprint` => `base_link` => `wheels`
is better.

@mum254 
Thank you for your suggestion.

**Comment by RyodoTanaka** [comment]
@AriYu 
Sorry, I had mistake.

> First, I set the base_footprint be transformed from base_link.

That's not correct. I wanted to say 

> I set the base_link be transformed from base_footprint.

I mean, I set the tree `base_footprint` -> `base_link`.
If you want to check that, go 72001a6bd18ebd8427af832ac2ffb376a0ec905f.
And on the next commit (c9a5be3752d1d337ee8d7d0097c058869a3e1279), I changed that to now we use.

**Comment by RyodoTanaka** [comment]
@AriYu 
Now, we don't use the gear on the middle of the robot. Because, we need more resource for calculation and the model would be more complex to simulate.
But, we have never tried that. And, we have another problem on the tf tree.
So now, It worth to add the gear on the simulated model I think.
Even if we need to recreate some stl files... 
Please give me your opinion.

**Comment by AriYu** [comment]
@RyodoTanaka 
OK, I see.
For the time being, I will go under this structure of tf tree.
If we found better solution, fix this problem.
So, this issue will not close until this problem is solved.

**Comment by AriYu** [comment]
In `fix-tf-tree` branch, we tried new structure of tf tree fr01.
A new structure of tf tree is like this.
`base_footprint` => `base_stabilized` => `base_link` => `other_links`
I referenced `hector_slam` tutorial. That link is [here](http://wiki.ros.org/hector_slam/Tutorials/SettingUpForYourRobot).
And, this structure looks no problems.
[fr01_modified_TF_tree.pdf](https://github.com/Nishida-Lab/forest_robot_project/files/152457/fr01_modified_TF_tree.pdf)
But, the modify will influence other programs such as using `fake_base_footprint`, because `fake_base_footprint` is deleted. Then, some other problems maybe occur. 
So, I want to get your agreement.
Thank you @RyodoTanaka
