### ISSUE TITLE
Please tell me wheel radius and width!

### ISSUE THREAD

**Issue by MoriKen254** [Nishida-Lab/forest_robot_project#20]
As mentioned in the title. I couldn't figure them out from a collada format file lol.
## background

I'm trying to apply [diff_drive_controller](http://wiki.ros.org/diff_drive_controller) to the robot as start up.

The controller requires the radius and width of wheels, which are used to compute kinematics of the model inside and should be needed for our robot  model as well.

**Comment by AriYu** [comment]
@mum254 
I understood. That's great.
Wheel diameter is 0.16[m], so the radius is 0.08[m].
And width of wheels is 0.13[m].
If you want to get some other parameters, please feel free to ask anything.

**Comment by MoriKen254** [comment]
@AriYu 
Thanks. I'll surely ask something again.
