### ISSUE TITLE
Could you remove the namespace `fr01` from the urdf model?

### ISSUE THREAD

**Issue by MoriKen254** [Nishida-Lab/forest_robot_project#21]
As mention in the title. If the request is accepted, I want you check all the compatibility about namespace other than the things I noted below. That's why I didn't send pull request directly.

That's because diff_drive_controller doesn't seem to support namespace so the original model with namespace doesn't response when it gets cmd_vel topic. Other robots on github using the controller don't seem to use namespace either I searched so far.

Thus firstly, I tried several approaches to keep namespace `fr01` while removing the namespace when applying diff_drive_controller. However, all of them didn't worked well to the extend I worked on.

The only and the simplest way is just removing the namespace from urdf. (To be honest, I don't wanna take looooong time to fix files to remain this namespace stuff lol.)

Then I change files as follows:
- removed `fr01` from control yaml file,
- removed `ns` property of `controller spawner` and <remap> tag of `robot_state_publisher` in fr01_sim_control.launch,
- removed <robotNamespace> tag from gazebo plugin load tag in fr01.urdf.xacro.

After that, gazebo model started to run with cmd_vel, and everything seems going well. If possible, please remove namespace like above and fix related items you guys know.

Thanks.

**Comment by AriYu** [comment]
I see. It looks difficult to keep namespace `fr01`.
So, you can remove it and please pull request.
I think the gazebo model is independent other packages, so the effect is minimum. If there are some problem, I will fix it.

**Comment by MoriKen254** [comment]
@AriYu 
Thanks. I'll push it later. 
Let's implement the driver with a simple one at first and solve the namespace issue if another one gets needed =-)

**Comment by AriYu** [comment]
@mum254 
I see. Thanks.

**Comment by MoriKen254** [comment]
sent a request related on this issue. closing.
