### ISSUE TITLE
What the reason to specify hardware interface in transmission tag of Rocker and Bogie joints.

### ISSUE THREAD

**Issue by MoriKen254** [Nishida-Lab/forest_robot_project#22]
As mentioned in the title.
In my understanding, hardware interface is needed when the joint is actively controlled but hardware interface is specified for the Rocker and Bogie joints although they are passive. Thus I don't believe hardware interface is required for the joints. 

How do you think about it?

If I make some mistakes, please point them out. Thanks.

**Comment by AriYu** [comment]
Sorry, I don't understand perfectly.
Is this problem in Gazebo model ? So, the problem is that a hardware interface for Rocker and Bogie joint is defined in Gazemo model, isn't it ?

**Comment by MoriKen254** [comment]
@AriYu 
Actually, it doesn't cause any problem on the model so far =-).
I'm just concerned about its redundancy.  

Moreover, I believe the joints should never affect the other issue on diff_drive_controller. I already tried to apply the controller with the hardware interface of the Rocker and Bogie joints commented out but the issue still remained.

To sum up, If there is no reason to assign hardware interface to the joints, please let me refactor the related property when I remove namespace.

Thanks.

**Comment by AriYu** [comment]
@MoriKen254 
I asked @RyodoTanaka about the joint. 
He say that the hardware interface of the Rocker and Bogie joints play a roll in publishing the joint state. If there isn't the hardware interface, the display of Rocker and Bogie in `rviz` will be fixed (not moving).

If I'm wrong or misreading, please point out to me.

**Comment by MoriKen254** [comment]
@AriYu 
Ohh, that makes sense! All clear! Thanks.

**Comment by AriYu** [comment]
@mum254 
That sounds good.

**Comment by MoriKen254** [comment]
The issue got resolved. closing.
