### ISSUE TITLE
Error occured when I used rosdep command.

### ISSUE THREAD

**Issue by AriYu** [Nishida-Lab/forest_robot_project#8]
When I was doing installation following wiki, I ran into error. Why ?

``` bash
$ rosdep install -i --from-paths src
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
fr01_gazebo: Cannot locate rosdep definition for [forest_robot_control]
```

**Comment by RyodoTanaka** [comment]
@AriYu 
I already fixed that error on the newest master branch.
So, please check that and If it works, close this issue.

**Comment by AriYu** [comment]
@RyodoTanaka 
Thank you for your great work !
I confirmed there were no errors.
So, I will close this issue.
